### PR TITLE
postgres_scanner plugin

### PR DESCRIPTION
**Pull request by obronco**

### CODE REVIEW

**Comment by obronco** [comment]
https://duckdb.org/2022/09/30/postgres-scanner.html

**Comment by jwills** [comment]
Looks like this one got conflated with your s3 profile one-- let's rebase it and take another look? And was the intent here just to switch the postgres plugin over to use the postgres_scanner extension in DuckDB?

**Comment by obronco** [comment]
Sorry about the S3 stuff. Regarding postgres_scanner, I added it for personal use because of performance issues I was having with the default postgres plugin. I thought it would help others.

**Comment by jwills** [comment]
Closing this out in favor of a more recent PR for the postgres plugin

**Pull request closed without merging**
