### PR TITLE
Revert commits

### PR DESCRIPTION
**Pull request by dan1elt0m**

### CODE REVIEW

**Comment by jwills** [comment]
@dan1elt0m this looks interesting, but I must be missing some context on what you all are cooking here (or possibly this was meant for a fork of this repo for now?)

**Comment by dan1elt0m** [comment]
Hey Josh, First of all, thanks for creating this great library! My apologies for creating this PR here. Indeed ment for a fork. I'm experimenting with running dbt-duckdb against the OSS Unity Catalog using a unity plugin. 

Would like to come back later to create an actual PR if you're interested. Probably after delta plugin is merged, because it depends heavily on that.

**Comment by jwills** [comment]
No worries man, thank you for the kind words! I'm interested in making dbt-duckdb work with all kinds of catalogs, so when you have something that works, let me know!

**Comment by dan1elt0m** [comment]
That's great. I'll surely do that.

**Pull request closed without merging**
