### PR TITLE
Update `dateadd` to work with new `datediff`

### LINKED ISSUE #346: Bug - Issue with dateadd since 1.7.2 and the update of `date_diff`
The following model worked in <1.7.2 but fails in 1.7.2

```
{{
    config(
        materialized = 'table',
    )
}}


{% set date_expr = "current_date()" if target.type in ["duckdb"] else dbt.current_timestamp() %}
with days as (

    {{
        dbt_utils.date_spine(
            'day',
            date_expr,
            dbt.dateadd('day', 1, date_expr),
        )
    }}

),

final as (
    select cast(date_day as date) as date_day
    from days
)

select * from final
```

The error is

```
  Runtime Error in model spine (models/spine.sql)
    Binder Error: No function matches the given name and argument types '+(DATE, TIMESTAMP)'. You might need to add explicit type casts.
        Candidate functions:
        +(TINYINT) -> TINYINT
        +(TINYINT, TINYINT) -> TINYINT
        +(SMALLINT) -> SMALLINT
        +(SMALLINT, SMALLINT) -> SMALLINT
        +(INTEGER) -> INTEGER
        +(INTEGER, INTEGER) -> INTEGER
        +(BIGINT) -> BIGINT
        +(BIGINT, BIGINT) -> BIGINT
        +(HUGEINT) -> HUGEINT
        +(HUGEINT, HUGEINT) -> HUGEINT
        +(FLOAT) -> FLOAT
        +(FLOAT, FLOAT) -> FLOAT
        +(DOUBLE) -> DOUBLE
        +(DOUBLE, DOUBLE) -> DOUBLE
        +(DECIMAL) -> DECIMAL
        +(DECIMAL, DECIMAL) -> DECIMAL
        +(UTINYINT) -> UTINYINT
        +(UTINYINT, UTINYINT) -> UTINYINT
        +(USMALLINT) -> USMALLINT
        +(USMALLINT, USMALLINT) -> USMALLINT
        +(UINTEGER) -> UINTEGER
        +(UINTEGER, UINTEGER) -> UINTEGER
        +(UBIGINT) -> UBIGINT
        +(UBIGINT, UBIGINT) -> UBIGINT
        +(DATE, INTEGER) -> DATE
        +(INTEGER, DATE) -> DATE
        +(INTERVAL, INTERVAL) -> INTERVAL
        +(DATE, INTERVAL) -> DATE
        +(INTERVAL, DATE) -> DATE
        +(TIME, INTERVAL) -> TIME
        +(INTERVAL, TIME) -> TIME
        +(TIMESTAMP, INTERVAL) -> TIMESTAMP
        +(INTERVAL, TIMESTAMP) -> TIMESTAMP
        +(TIME, DATE) -> TIMESTAMP
        +(DATE, TIME) -> TIMESTAMP
        +(ANY[], ANY[]) -> ANY[]
        +(TIMESTAMP WITH TIME ZONE, INTERVAL) -> TIMESTAMP WITH TIME ZONE
        +(INTERVAL, TIMESTAMP WITH TIME ZONE) -> TIMESTAMP WITH TIME ZONE
    
    LINE 6:     current_date() + ((interval '1 day') * (1))
```

After some troubleshooting, it seems to be related to the update version of `duckdb__datediff` in 1.7.2

### PR DESCRIPTION
**Pull request by b-per**
Fixes #346 

Tested locally. 

The model from the issue fails with 1.7.2 but works with the code from this branch,

### CODE REVIEW

**Comment by jwills** [comment]
Could we turn the model that fails into a test w/o too much trouble?

**Comment by b-per** [comment]
Yep, I can do that

**Comment by jwills** [comment]
(don't worry about the motherduck test)

**Comment by b-per** [comment]
I checked that the test was failing in 1.7.2 and passing locally in my branch

**Comment by jwills** [comment]
grateful for this @b-per

**Pull request merged**
